# Generated by Django 5.1.1 on 2026-03-06 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('category', models.CharField(choices=[('Billing', 'Billing'), ('Refund', 'Refund'), ('Account Access', 'Account Access'), ('Cancellation', 'Cancellation'), ('General Inquiry', 'General Inquiry')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
